### ISSUE TITLE
Stack trace on Ubuntu 16.10.

### ISSUE THREAD

**Issue by trhd** [dmedvinsky/mutt-ics#16]
```
[-- Autoview using mutt-ics --]
[-- Autoview stderr of mutt-ics --]
Traceback (most recent call last):
  File "/home/hniemine/.local/bin//mutt-ics", line 11, in <module>
    sys.exit(entry_point())
  File "/home/hniemine/.local/lib/python3.5/site-packages/mutt_ics/mutt_ics.py", line 150, in entry_point
    return main(sys.argv)
  File "/home/hniemine/.local/lib/python3.5/site-packages/mutt_ics/mutt_ics.py", line 144, in main
    output = get_interesting_stuff(cal)
  File "/home/hniemine/.local/lib/python3.5/site-packages/mutt_ics/mutt_ics.py", line 56, in get_interesting_stuff
    c = get_component(component)
  File "/home/hniemine/.local/lib/python3.5/site-packages/mutt_ics/mutt_ics.py", line 69, in get_component
    return get_event(component)
  File "/home/hniemine/.local/lib/python3.5/site-packages/mutt_ics/mutt_ics.py", line 128, in get_event
    result = filter(bool, [get_header(e),
  File "/home/hniemine/.local/lib/python3.5/site-packages/mutt_ics/mutt_ics.py", line 99, in get_header
    get_val('DTSTART', format_date)
  File "/home/hniemine/.local/lib/python3.5/site-packages/mutt_ics/mutt_ics.py", line 95, in get_val
    vals.append((name_map[name], f(e[name])))
  File "/home/hniemine/.local/lib/python3.5/site-packages/mutt_ics/mutt_ics.py", line 79, in format_date
    return x.dt.astimezone(tz.tzlocal()).strftime(datefmt)
AttributeError: 'datetime.date' object has no attribute 'astimezone'
```

Has possibly something to do with repeating events or events lasting for several days since happens with only some ics files.

```
$ pip3 show mutt-ics
---
Metadata-Version: 2.0
Name: mutt-ics
Version: 0.7
Summary: A tool to show calendar event details in Mutt.
Home-page: https://github.com/dmedvinsky/mutt-ics
Author: Dmitry Medvinsky
Author-email: me@dmedvinsky.name
Installer: pip
License: MIT
Location: /home/hniemine/.local/lib/python3.5/site-packages
Requires: icalendar
Classifiers:
  Development Status :: 3 - Alpha
  License :: OSI Approved :: MIT License
Entry-points:
  [console_scripts]
  mutt-ics = mutt_ics.mutt_ics:entry_point
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Working event:
```
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:(UTC+02:00) Helsinki\, Kyiv\, Riga\, Sofia\, Tallinn\, Vilnius
BEGIN:STANDARD
DTSTART:16010101T040000
TZOFFSETFROM:+0300
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0300
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN=trhd:MAILTO:trhd@iki.fi
DESCRIPTION;LANGUAGE=en-US:foobar\n
SUMMARY;LANGUAGE=en-US:test event
DTSTART;TZID="(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius":2016
 1224T080000
DTEND;TZID="(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius":201612
 25T083000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20161222T131417Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION;LANGUAGE=en-US:
END:VEVENT
END:VCALENDAR
```

Broken event:
```
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:(UTC+02:00) Helsinki\, Kyiv\, Riga\, Sofia\, Tallinn\, Vilnius
BEGIN:STANDARD
DTSTART:16010101T040000
TZOFFSETFROM:+0300
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0300
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN=trhd:MAILTO:trhd@iki.fi
DESCRIPTION;LANGUAGE=en-US:foobar\n
SUMMARY;LANGUAGE=en-US:test event
DTSTART;VALUE=DATE:20161224
DTEND;VALUE=DATE:20161226
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20161222T131538Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION;LANGUAGE=en-US:
END:VEVENT
END:VCALENDAR
```

**Comment by trhd** [comment]
Could be related to this line on the ics file:

TZID:FLE Standard Time

**Comment by dmedvinsky** [comment]
Hey @trhd, I've fixed this and published the new version. Please, give it a try and check if the fix worked for you.

**Comment by trhd** [comment]
Looks good now.
